import { Duty } from "./types";

export const DUTIES_MOCK: Duty[] = [
  {
    id: "1",
    name: "qa-midnight-duty",
    duty_type: "weekdays",
    slack_group_id: "S043HC6839V",
    members: ["dmitrymt", "shakirov-av", "evgenijgl"],
  },
  {
    id: "2",
    name: "qa-offline-midnight-duty",
    duty_type: "weekly",
    duty_change_day: 1,
    slack_group_id: "S066GRZS0B0",
    members: [
      "dmitrii-shein",
      "nonideal",
      "elena-kostuchenko",
      "evgenijgl",
      "shakirov-av",
    ],
  },
  {
    id: "3",
    name: "geometry-planner-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S048TU68AVC",
    members: ["commandos", "kswaldemar"],
  },
  {
    id: "4",
    name: "scoring-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S04DEEEA5R7",
    members: ["prime-eugene", "avolchek", "georgymironov"],
  },
  {
    id: "5",
    name: "prediction-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S049F6X97V1",
    members: ["irina-rud", "gerrok", "ionov", "mstebelev"],
  },
  {
    id: "6",
    name: "rbl-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S04APEWUBD3",
    members: [
      "dasimagin",
      "kolo-yury",
      "aleksey-titov",
      "oleg-popkov",
      "tonysky",
    ],
  },
  {
    id: "7",
    name: "simulation-duty",
    duty_type: "weekly",
    duty_change_day: 4,
    slack_group_id: "S04466HPQ13",
    members: ["atm", "hertz", "electricsheep"],
  },
  {
    id: "8",
    name: "delivery-rc-duty",
    duty_type: "weekly",
    duty_change_day: 1,
    slack_group_id: "S04A4CLU2G2",
    members: ["atn18", "smdenis", "serg-salnikov", "gus3inov", "shchupakov"],
  },
  {
    id: "9",
    name: "cd-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S0459FCT5FW",
    members: ["astrike", "draif"],
  },
  {
    id: "10",
    name: "ci-duty",
    duty_type: "weekly",
    duty_change_day: 1,
    slack_group_id: "S04AXGDAUHX",
    members: ["artyrian", "gorshkovna", "iniklyaev"],
  },
  {
    id: "11",
    name: "yield-duty",
    duty_type: "regular",
    duty_length: 2,
    slack_group_id: "S049Q7UC6GZ",
    members: ["artfulvampire", "reshetkov"],
  },
  {
    id: "12",
    name: "pedestrian-duty",
    duty_type: "regular",
    duty_length: 2,
    slack_group_id: "S04996ZRHAR",
    members: ["artfulvampire", "mzhuryk"],
  },
  {
    id: "13",
    name: "cloud-platform-duty",
    duty_type: "regular",
    duty_length: 1,
    slack_group_id: "S04BVSL9FHQ",
    members: ["hammet", "mossad", "evgenymarkov"],
  },
  {
    id: "14",
    name: "sysinfra-duty",
    duty_type: "regular",
    duty_length: 3,
    slack_group_id: "S046JKDQW11",
    members: ["gerasiov", "zaripov-kamil", "msaristov", "matshch", "esmukov"],
  },
  {
    id: "15",
    name: "hil-duty",
    duty_type: "regular",
    duty_length: 3,
    slack_group_id: "S04785MN3PW",
    members: ["gerasiov", "zaripov-kamil", "msaristov", "matshch", "esmukov"],
  },
  {
    id: "16",
    name: "simulation-pipeline-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S0626P9UWPQ",
    members: ["rusabakumov", "andreyol", "unkulunkulu"],
  },
  {
    id: "17",
    name: "logs-duty",
    duty_type: "regular",
    duty_length: 3,
    slack_group_id: "S044Y18M1DJ",
    members: ["gerasiov", "zaripov-kamil", "msaristov", "matshch", "esmukov"],
  },
  {
    id: "18",
    name: "av-platform-duty",
    duty_type: "weekly",
    duty_change_day: 0,
    slack_group_id: "S06592HEEF4",
    members: ["artyrian", "iniklyaev", "gorshkovna", "astrike"],
  },
  {
    id: "19",
    name: "pipeline-duty",
    duty_type: "regular",
    duty_length: 3,
    slack_group_id: "S06HFA5R8BC",
    members: ["rusabakumov", "sokursky", "unkulunkulu", "andreyol"],
  },
];

export const USERS_MOCK = [
  {
    login: "dmitrymt",
    slack_id: "U048S5A963F",
  },
  {
    login: "shakirov-av",
    slack_id: "U044NDGSZK9",
  },
  {
    login: "evgenijgl",
    slack_id: "U048W75N6E7",
  },
  {
    login: "trinboz",
    slack_id: "U048E76PHNK",
  },
  {
    login: "taqumi",
    slack_id: "U04977N0TGR",
  },
  {
    login: "dmitrii-shein",
    slack_id: "U04280PH879",
  },
  {
    login: "nonideal",
    slack_id: "U03VA9BGGGG",
  },
  {
    login: "elena-kostuchenko",
    slack_id: "U0432TT7FBK",
  },
  {
    login: "prime-eugene",
    slack_id: "U03V09FCFG9",
  },
  {
    login: "avolchek",
    slack_id: "U043FHL2BL7",
  },
  {
    login: "georgymironov",
    slack_id: "U045E5A5JRM",
  },
  {
    login: "irina-rud",
    slack_id: "U045045H9EV",
  },
  {
    login: "gerrok",
    slack_id: "U04578ES8SW",
  },
  {
    login: "ionov",
    slack_id: "U043VPNV5C6",
  },
  {
    login: "mstebelev",
    slack_id: "U044FSN802D",
  },
  {
    login: "dasimagin",
    slack_id: "U03UMH89STD",
  },
  {
    login: "kolo-yury",
    slack_id: "U03U7CXRW5D",
  },
];
